version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gotube
      TZ: UTC
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # bot:
  #   container_name: gotube_bot
  #   build: .4
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./configs:/app/configs
  #   environment:
  #     - TZ=UTC
  #   restart: unless-stopped

volumes:
  postgres_data:
